apiVersion: v1
kind: Service
metadata:
  name: user-profile-service
  namespace: fitquest
  labels:
    app: user-profile-service
spec:
  type: ClusterIP
  selector:
    app: user-profile-service
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  sessionAffinity: None
