require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '16.0'

# Add sources for CocoaPods
source 'https://github.com/CocoaPods/Specs.git'

target 'FitQuest' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
