apiVersion: v1
kind: Service
metadata:
  name: SERVICE_NAME
  namespace: fitquest
  labels:
    app: SERVICE_NAME
    version: v1
spec:
  type: ClusterIP
  selector:
    app: SERVICE_NAME
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: SERVICE_NAME-headless
  namespace: fitquest
  labels:
    app: SERVICE_NAME
spec:
  clusterIP: None
  selector:
    app: SERVICE_NAME
  ports:
    - name: http
      port: 5000
      targetPort: 5000
