apiVersion: v1
kind: Service
metadata:
  name: sync-service
  namespace: fitquest
  labels:
    app: sync-service
spec:
  type: ClusterIP
  selector:
    app: sync-service
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  sessionAffinity: None
