---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  namespace: monitoring
  labels:
    app: jaeger
spec:
  type: ClusterIP
  ports:
    - name: zipkin-thrift
      port: 5775
      targetPort: jaeger-agent-zipkin-thrift
      protocol: UDP
    - name: compact
      port: 6831
      targetPort: jaeger-agent-compact
      protocol: UDP
    - name: binary
      port: 6832
      targetPort: jaeger-agent-binary
      protocol: UDP
    - name: serve-configs
      port: 5778
      targetPort: jaeger-agent-serve-configs
      protocol: TCP
  selector:
    app: jaeger

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: monitoring
  labels:
    app: jaeger
spec:
  type: ClusterIP
  ports:
    - name: jaeger-collector
      port: 14268
      targetPort: jaeger-collector
      protocol: TCP
    - name: jaeger-collector-grpc
      port: 14250
      targetPort: jaeger-collector-grpc
      protocol: TCP
  selector:
    app: jaeger

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: monitoring
  labels:
    app: jaeger
spec:
  type: ClusterIP
  ports:
    - name: query
      port: 16686
      targetPort: jaeger-query
      protocol: TCP
  selector:
    app: jaeger
